resources:
- openstack_v1alpha1_openstackcloud.yaml
- openstack_v1alpha1_openstackflavor.yaml
- openstack_v1alpha1_openstackfloatingip.yaml
- openstack_v1alpha1_openstackimage.yaml
- openstack_v1alpha1_openstacknetwork.yaml
- openstack_v1alpha1_openstacksecuritygrouprule.yaml
- openstack_v1alpha1_openstacksecuritygroup.yaml
- openstack_v1alpha1_openstackserver.yaml
- openstack_v1alpha1_openstacksubnet.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
