on:
  push:
    branches:
    - main
  pull_request:
name: e2e

jobs:
  functional-compute:
    strategy:
      matrix:
        include:
          # - name: "zed"
          #   openstack_version: "stable/zed"
          #   ubuntu_version: "20.04"
          # - name: "antelope"
          #   openstack_version: "stable/2023.1"
          #   ubuntu_version: "22.04"
          - name: "bobcat"
            openstack_version: "stable/2023.2"
            ubuntu_version: "22.04"
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: Deploy OpenStack ${{ matrix.name }} and run acceptance tests
    steps:
      - uses: actions/checkout@v4

      - name: Deploy devstack
        uses: EmilienM/devstack-action@40c77372dbc135a17adc877eb77fc226a134305c
        with:
          enable_workaround_docker_io: 'false'
          branch: ${{ matrix.openstack_version }}

      - name: Kind Cluster
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140
        with:
          cluster_name: orc

      - name: Explore the cloud
        run: |
          echo NETWORKS
          openstack network list
          echo PUBLIC
          openstack network show public
          echo FLAVORS
          openstack flavor list
          echo IMAGE
          openstack image list
        env:
          OS_CLOUD: devstack

      - name: Prepare kubebuilder
        run: make

      - name: Get a clouds.yaml
        run: cp /etc/openstack/clouds.yaml config/samples/simple-server/

      - name: Run orc
        run: |
          kubectl config use-context kind-orc
          make install
          make run & sleep 5
          kubectl apply -k config/samples/simple-server
          kubectl wait --timeout=10m --for=condition=ready OpenStackServer workstation
