name: e2e
on:
  pull_request:
env:
  image_tag_commit: quay.io/orc/orc-pr:commit-${GITHUB_SHA::7}
permissions:
  contents: read
jobs:
  e2e:
    strategy:
      matrix:
        include:
          # - name: "zed"
          #   openstack_version: "stable/zed"
          #   ubuntu_version: "20.04"
          # - name: "antelope"
          #   openstack_version: "stable/2023.1"
          #   ubuntu_version: "22.04"
          - name: "bobcat"
            openstack_version: "stable/2023.2"
            ubuntu_version: "22.04"

    runs-on: ubuntu-${{ matrix.ubuntu_version }}

    name: Run acceptance tests against OpenStack ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v4

    - name: Build and push a container image
      run: |
        docker login -u="${{ secrets.QUAY_USERNAME }}" -p="${{ secrets.QUAY_TOKEN }}" quay.io
        docker build -t ${{ env.image_tag_commit }} --label quay.expires-after=4h .
        docker push ${{ env.image_tag_commit }}

    - name: Deploy devstack
      uses: EmilienM/devstack-action@40c77372dbc135a17adc877eb77fc226a134305c
      with:
        enable_workaround_docker_io: 'false'
        branch: ${{ matrix.openstack_version }}

    - name: Deploy a Kind Cluster
      uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140
      with:
        cluster_name: orc

    - name: Deploy orc
      run: |
        kubectl config use-context kind-orc
        make deploy IMG=${{ env.image_tag_commit }}

    - name: Apply simple-server
      run: |
        cp /etc/openstack/clouds.yaml config/samples/simple-server/
        kubectl apply -k config/samples/simple-server
        kubectl wait --timeout=10m --for=condition=ready OpenStackServer workstation

    - name: Explore the cloud
      run: |
        echo NETWORKS
        openstack network list
        echo PUBLIC
        openstack network show public
        echo FLAVORS
        openstack flavor list
        echo IMAGE
        openstack image list
        echo SERVER
        openstack server list
      env:
        OS_CLOUD: devstack
