on:
  push:
    branches:
    - main
  pull_request:
name: verify
permissions:
  contents: read

jobs:
  make-generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          make verify
